#!/usr/bin/env python3

import sys
import os
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        print("Usage: ./tweets @twitter_account")
        return

    # get last 50 tweets from user
    tweets = helpers.get_user_timeline(sys.argv[1], 50)

    # check if we have tweets
    if not tweets:
        print("failed to get tweets")
        return

    # links to files with negative and positive words
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # create analyzer
    analyzer = Analyzer(positives, negatives)

    # iterate through each tweet
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))

if __name__ == "__main__":
    main()
